/*
elev8er Public API

Testing VisualTestsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package elev8erpublicapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/elev8er/elev8er-go-sdk"
)

func Test_elev8erpublicapi_VisualTestsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VisualTestsAPIService CreateVisualTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VisualTestsAPI.CreateVisualTest(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService CreateVisualTestVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VisualTestsAPI.CreateVisualTestVersion(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService DeleteVisualTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.VisualTestsAPI.DeleteVisualTest(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService GetVisualTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VisualTestsAPI.GetVisualTest(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService GetVisualTestVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var versionId string

		resp, httpRes, err := apiClient.VisualTestsAPI.GetVisualTestVersion(context.Background(), id, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService ListVisualTestVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VisualTestsAPI.ListVisualTestVersions(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService ListVisualTests", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VisualTestsAPI.ListVisualTests(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService RollbackVisualTestVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var versionId string

		resp, httpRes, err := apiClient.VisualTestsAPI.RollbackVisualTestVersion(context.Background(), id, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService UpdateVisualTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VisualTestsAPI.UpdateVisualTest(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VisualTestsAPIService UpdateVisualTestVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var versionId string

		resp, httpRes, err := apiClient.VisualTestsAPI.UpdateVisualTestVersion(context.Background(), id, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
