/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProgramTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProgramTagRequest{}

// CreateProgramTagRequest struct for CreateProgramTagRequest
type CreateProgramTagRequest struct {
	Name string `json:"name"`
}

type _CreateProgramTagRequest CreateProgramTagRequest

// NewCreateProgramTagRequest instantiates a new CreateProgramTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProgramTagRequest(name string) *CreateProgramTagRequest {
	this := CreateProgramTagRequest{}
	this.Name = name
	return &this
}

// NewCreateProgramTagRequestWithDefaults instantiates a new CreateProgramTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProgramTagRequestWithDefaults() *CreateProgramTagRequest {
	this := CreateProgramTagRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateProgramTagRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProgramTagRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProgramTagRequest) SetName(v string) {
	o.Name = v
}

func (o CreateProgramTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProgramTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateProgramTagRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProgramTagRequest := _CreateProgramTagRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProgramTagRequest)

	if err != nil {
		return err
	}

	*o = CreateProgramTagRequest(varCreateProgramTagRequest)

	return err
}

type NullableCreateProgramTagRequest struct {
	value *CreateProgramTagRequest
	isSet bool
}

func (v NullableCreateProgramTagRequest) Get() *CreateProgramTagRequest {
	return v.value
}

func (v *NullableCreateProgramTagRequest) Set(val *CreateProgramTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProgramTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProgramTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProgramTagRequest(val *CreateProgramTagRequest) *NullableCreateProgramTagRequest {
	return &NullableCreateProgramTagRequest{value: val, isSet: true}
}

func (v NullableCreateProgramTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProgramTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


