/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
)

// checks if the UpdateProgramTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProgramTagRequest{}

// UpdateProgramTagRequest struct for UpdateProgramTagRequest
type UpdateProgramTagRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewUpdateProgramTagRequest instantiates a new UpdateProgramTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProgramTagRequest() *UpdateProgramTagRequest {
	this := UpdateProgramTagRequest{}
	return &this
}

// NewUpdateProgramTagRequestWithDefaults instantiates a new UpdateProgramTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProgramTagRequestWithDefaults() *UpdateProgramTagRequest {
	this := UpdateProgramTagRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateProgramTagRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProgramTagRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateProgramTagRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateProgramTagRequest) SetName(v string) {
	o.Name = &v
}

func (o UpdateProgramTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProgramTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUpdateProgramTagRequest struct {
	value *UpdateProgramTagRequest
	isSet bool
}

func (v NullableUpdateProgramTagRequest) Get() *UpdateProgramTagRequest {
	return v.value
}

func (v *NullableUpdateProgramTagRequest) Set(val *UpdateProgramTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProgramTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProgramTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProgramTagRequest(val *UpdateProgramTagRequest) *NullableUpdateProgramTagRequest {
	return &NullableUpdateProgramTagRequest{value: val, isSet: true}
}

func (v NullableUpdateProgramTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProgramTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


