/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessEnvelope{}

// SuccessEnvelope struct for SuccessEnvelope
type SuccessEnvelope struct {
	Success bool `json:"success"`
	Message *string `json:"message,omitempty"`
	Data interface{} `json:"data,omitempty"`
}

type _SuccessEnvelope SuccessEnvelope

// NewSuccessEnvelope instantiates a new SuccessEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessEnvelope(success bool) *SuccessEnvelope {
	this := SuccessEnvelope{}
	this.Success = success
	return &this
}

// NewSuccessEnvelopeWithDefaults instantiates a new SuccessEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessEnvelopeWithDefaults() *SuccessEnvelope {
	this := SuccessEnvelope{}
	return &this
}

// GetSuccess returns the Success field value
func (o *SuccessEnvelope) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *SuccessEnvelope) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *SuccessEnvelope) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SuccessEnvelope) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessEnvelope) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SuccessEnvelope) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SuccessEnvelope) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessEnvelope) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessEnvelope) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SuccessEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *SuccessEnvelope) SetData(v interface{}) {
	o.Data = v
}

func (o SuccessEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *SuccessEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessEnvelope := _SuccessEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessEnvelope)

	if err != nil {
		return err
	}

	*o = SuccessEnvelope(varSuccessEnvelope)

	return err
}

type NullableSuccessEnvelope struct {
	value *SuccessEnvelope
	isSet bool
}

func (v NullableSuccessEnvelope) Get() *SuccessEnvelope {
	return v.value
}

func (v *NullableSuccessEnvelope) Set(val *SuccessEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessEnvelope(val *SuccessEnvelope) *NullableSuccessEnvelope {
	return &NullableSuccessEnvelope{value: val, isSet: true}
}

func (v NullableSuccessEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


