/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ChatMessageInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatMessageInput{}

// ChatMessageInput struct for ChatMessageInput
type ChatMessageInput struct {
	// The user message to send to the agent.
	Message string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _ChatMessageInput ChatMessageInput

// NewChatMessageInput instantiates a new ChatMessageInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatMessageInput(message string) *ChatMessageInput {
	this := ChatMessageInput{}
	this.Message = message
	return &this
}

// NewChatMessageInputWithDefaults instantiates a new ChatMessageInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatMessageInputWithDefaults() *ChatMessageInput {
	this := ChatMessageInput{}
	return &this
}

// GetMessage returns the Message field value
func (o *ChatMessageInput) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ChatMessageInput) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ChatMessageInput) SetMessage(v string) {
	o.Message = v
}

func (o ChatMessageInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatMessageInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChatMessageInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatMessageInput := _ChatMessageInput{}

	err = json.Unmarshal(data, &varChatMessageInput)

	if err != nil {
		return err
	}

	*o = ChatMessageInput(varChatMessageInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChatMessageInput struct {
	value *ChatMessageInput
	isSet bool
}

func (v NullableChatMessageInput) Get() *ChatMessageInput {
	return v.value
}

func (v *NullableChatMessageInput) Set(val *ChatMessageInput) {
	v.value = val
	v.isSet = true
}

func (v NullableChatMessageInput) IsSet() bool {
	return v.isSet
}

func (v *NullableChatMessageInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatMessageInput(val *ChatMessageInput) *NullableChatMessageInput {
	return &NullableChatMessageInput{value: val, isSet: true}
}

func (v NullableChatMessageInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatMessageInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


