/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
)

// checks if the CreateAgentChatRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentChatRequest{}

// CreateAgentChatRequest struct for CreateAgentChatRequest
type CreateAgentChatRequest struct {
	Title *string `json:"title,omitempty"`
}

// NewCreateAgentChatRequest instantiates a new CreateAgentChatRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentChatRequest() *CreateAgentChatRequest {
	this := CreateAgentChatRequest{}
	return &this
}

// NewCreateAgentChatRequestWithDefaults instantiates a new CreateAgentChatRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentChatRequestWithDefaults() *CreateAgentChatRequest {
	this := CreateAgentChatRequest{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateAgentChatRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentChatRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateAgentChatRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateAgentChatRequest) SetTitle(v string) {
	o.Title = &v
}

func (o CreateAgentChatRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentChatRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableCreateAgentChatRequest struct {
	value *CreateAgentChatRequest
	isSet bool
}

func (v NullableCreateAgentChatRequest) Get() *CreateAgentChatRequest {
	return v.value
}

func (v *NullableCreateAgentChatRequest) Set(val *CreateAgentChatRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentChatRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentChatRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentChatRequest(val *CreateAgentChatRequest) *NullableCreateAgentChatRequest {
	return &NullableCreateAgentChatRequest{value: val, isSet: true}
}

func (v NullableCreateAgentChatRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentChatRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


