/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
)

// checks if the SetProgramTagsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetProgramTagsRequest{}

// SetProgramTagsRequest struct for SetProgramTagsRequest
type SetProgramTagsRequest struct {
	TagIds []string `json:"tagIds,omitempty"`
}

// NewSetProgramTagsRequest instantiates a new SetProgramTagsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetProgramTagsRequest() *SetProgramTagsRequest {
	this := SetProgramTagsRequest{}
	return &this
}

// NewSetProgramTagsRequestWithDefaults instantiates a new SetProgramTagsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetProgramTagsRequestWithDefaults() *SetProgramTagsRequest {
	this := SetProgramTagsRequest{}
	return &this
}

// GetTagIds returns the TagIds field value if set, zero value otherwise.
func (o *SetProgramTagsRequest) GetTagIds() []string {
	if o == nil || IsNil(o.TagIds) {
		var ret []string
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetProgramTagsRequest) GetTagIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TagIds) {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *SetProgramTagsRequest) HasTagIds() bool {
	if o != nil && !IsNil(o.TagIds) {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []string and assigns it to the TagIds field.
func (o *SetProgramTagsRequest) SetTagIds(v []string) {
	o.TagIds = v
}

func (o SetProgramTagsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetProgramTagsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TagIds) {
		toSerialize["tagIds"] = o.TagIds
	}
	return toSerialize, nil
}

type NullableSetProgramTagsRequest struct {
	value *SetProgramTagsRequest
	isSet bool
}

func (v NullableSetProgramTagsRequest) Get() *SetProgramTagsRequest {
	return v.value
}

func (v *NullableSetProgramTagsRequest) Set(val *SetProgramTagsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetProgramTagsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetProgramTagsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetProgramTagsRequest(val *SetProgramTagsRequest) *NullableSetProgramTagsRequest {
	return &NullableSetProgramTagsRequest{value: val, isSet: true}
}

func (v NullableSetProgramTagsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetProgramTagsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


