/*
elev8er Public API

Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 

API version: 1.0.0
Contact: support@elev8er.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elev8erpublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSessionStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSessionStatusRequest{}

// UpdateSessionStatusRequest struct for UpdateSessionStatusRequest
type UpdateSessionStatusRequest struct {
	Status string `json:"status"`
}

type _UpdateSessionStatusRequest UpdateSessionStatusRequest

// NewUpdateSessionStatusRequest instantiates a new UpdateSessionStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSessionStatusRequest(status string) *UpdateSessionStatusRequest {
	this := UpdateSessionStatusRequest{}
	this.Status = status
	return &this
}

// NewUpdateSessionStatusRequestWithDefaults instantiates a new UpdateSessionStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSessionStatusRequestWithDefaults() *UpdateSessionStatusRequest {
	this := UpdateSessionStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateSessionStatusRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateSessionStatusRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateSessionStatusRequest) SetStatus(v string) {
	o.Status = v
}

func (o UpdateSessionStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSessionStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateSessionStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSessionStatusRequest := _UpdateSessionStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSessionStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateSessionStatusRequest(varUpdateSessionStatusRequest)

	return err
}

type NullableUpdateSessionStatusRequest struct {
	value *UpdateSessionStatusRequest
	isSet bool
}

func (v NullableUpdateSessionStatusRequest) Get() *UpdateSessionStatusRequest {
	return v.value
}

func (v *NullableUpdateSessionStatusRequest) Set(val *UpdateSessionStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSessionStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSessionStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSessionStatusRequest(val *UpdateSessionStatusRequest) *NullableUpdateSessionStatusRequest {
	return &NullableUpdateSessionStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateSessionStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSessionStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


